# Generated by Django 3.2.3 on 2021-06-16 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0002_alter_persona_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zona',
            name='municipio',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
